gantt
    title Life Events Timeline
    todayMarker off


    dateFormat  YYYY-MM-DD
    axisFormat %Y


    section Professional Experience
    Partners in Health :milestone, 2010-06-01, 3m
    UCSF         :milestone, 2011-06-01, 3m1
    Beth Israel Deaconess Medical Center :milestone, 2012-06-01, 3m
    Software Engineer, Fiksu : 2014-01-01, 2014-06-30
    Adjunct Professor, Hampshire College : 2014-01-01, 2014-06-30
    Lead Instructor, Fullstack Academy : 2014-07-01, 2017-02-28
    CTO, CoLane : 2016-11-01, 2019-12-01
    Head of Tech, GetFrank, PBC : 2019-12-01, 2021-10-31
    Principal Engineer, StitchFix : 2021-10-31, 2022-08-01
    Staff Engineer, Amazon/One Medical : 2022-08-01, 2024-05-25

    
    section Writing & Projects
    Periodic Table Visualization :milestone, 2011-10-25, 0d
    Researchers, Hire Hackers, :milestone, 2013-05-01, 0d
    Async/Await Presentation :milestone, 2016-02-25, 0d
    #walkthevote :milestone, 2020-08-25, 0d

    section Education
    Hampshire College :hampshire : 2009-09-01, 2013-05-30
    
    section Residency
    %% California : 1991-04-29, 2009-08-31
    Amherst, MA : 2009-09-01, 2010-05-30
    Boston, MA : 2010-05-30, 2010-08-31
    Amherst, MA : 2010-09-01, 2011-05-30
    San Francisco, CA : 2011-05-30, 2011-08-31
    Amherst, MA : 2011-09-01, 2012-05-30
    Boston, MA : 2012-05-30, 2012-08-31
    Amherst, MA : 2012-09-01, 2014-06-30
    New York, NY : 2014-06-30, 2015-08-30
    Chicago, IL : 2015-08-30, 2024-05-25
